"""Initial migration with all 7 entities

Revision ID: 009bc3591fc6
Revises: 
Create Date: 2025-11-11 14:53:05.439156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '009bc3591fc6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('generation_requests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('guild_id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('thread_id', sa.String(length=32), nullable=False),
    sa.Column('original_instruction', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('generation_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_generation_requests_guild_id'), ['guild_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_generation_requests_thread_id'), ['thread_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_generation_requests_user_id'), ['user_id'], unique=False)

    op.create_table('global_settings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('guild_id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=True),
    sa.Column('default_model', sa.String(length=255), nullable=True),
    sa.Column('default_lora_list', sa.JSON(), nullable=True),
    sa.Column('default_prompt_suffix', sa.Text(), nullable=True),
    sa.Column('default_sd_params', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('global_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_global_settings_guild_id'), ['guild_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_global_settings_user_id'), ['user_id'], unique=False)

    op.create_table('lora_metadata',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('file_hash', sa.String(length=64), nullable=True),
    sa.Column('downloaded_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_path'),
    sa.UniqueConstraint('name')
    )
    op.create_table('queued_tasks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('task_type', sa.String(length=20), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('generation_metadata',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('request_id', sa.String(length=36), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('negative_prompt', sa.Text(), nullable=True),
    sa.Column('model_name', sa.String(length=255), nullable=False),
    sa.Column('lora_list', sa.JSON(), nullable=True),
    sa.Column('steps', sa.Integer(), nullable=False),
    sa.Column('cfg_scale', sa.Float(), nullable=False),
    sa.Column('sampler', sa.String(length=100), nullable=False),
    sa.Column('scheduler', sa.String(length=100), nullable=True),
    sa.Column('seed', sa.Integer(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('raw_params', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['generation_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('generated_images',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('request_id', sa.String(length=36), nullable=False),
    sa.Column('metadata_id', sa.String(length=36), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('discord_url', sa.String(length=512), nullable=True),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['metadata_id'], ['generation_metadata.id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['generation_requests.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_path')
    )
    op.create_table('thread_contexts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('guild_id', sa.String(length=32), nullable=False),
    sa.Column('thread_id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('generation_history', sa.JSON(), nullable=True),
    sa.Column('latest_metadata_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['latest_metadata_id'], ['generation_metadata.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('thread_id')
    )
    with op.batch_alter_table('thread_contexts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_thread_contexts_guild_id'), ['guild_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('thread_contexts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_thread_contexts_guild_id'))

    op.drop_table('thread_contexts')
    op.drop_table('generated_images')
    op.drop_table('generation_metadata')
    op.drop_table('queued_tasks')
    op.drop_table('lora_metadata')
    with op.batch_alter_table('global_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_global_settings_user_id'))
        batch_op.drop_index(batch_op.f('ix_global_settings_guild_id'))

    op.drop_table('global_settings')
    with op.batch_alter_table('generation_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_generation_requests_user_id'))
        batch_op.drop_index(batch_op.f('ix_generation_requests_thread_id'))
        batch_op.drop_index(batch_op.f('ix_generation_requests_guild_id'))

    op.drop_table('generation_requests')
    # ### end Alembic commands ###
