"""add_new_settings_fields

Revision ID: 92746fe8181c
Revises: 22b435d1c0a2
Create Date: 2025-11-17 14:53:59.878805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92746fe8181c'
down_revision: Union[str, Sequence[str], None] = '22b435d1c0a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('global_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seed', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('batch_size', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('batch_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('hires_upscaler', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('hires_steps', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('denoising_strength', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('upscale_by', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('refiner_checkpoint', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('refiner_switch_at', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('global_settings', schema=None) as batch_op:
        batch_op.drop_column('refiner_switch_at')
        batch_op.drop_column('refiner_checkpoint')
        batch_op.drop_column('upscale_by')
        batch_op.drop_column('denoising_strength')
        batch_op.drop_column('hires_steps')
        batch_op.drop_column('hires_upscaler')
        batch_op.drop_column('batch_count')
        batch_op.drop_column('batch_size')
        batch_op.drop_column('seed')

    # ### end Alembic commands ###
